branches:
  - master
  - release-drafter  # for testing edits to this configuration

name-template: 'Version $RESOLVED_VERSION'
tag-template: 'v$RESOLVED_VERSION'

sort-by: title # sort alphabetically
sort-direction: ascending

categories:
  - title: '### NEW:'
    labels:
      - 'pr/feature'
  - title: '### FIXED:'
    labels:
      - 'pr/bug-fix'
  - title: '### IMPROVED:'
    labels:
      - 'pr/optimization'
  - title: '### CHANGED:'
    labels:
      - 'pr/change'
  - title: '### SETTINGS:'
    labels:
      - 'pr/setting'
  - title: '### TRANSLATION:'
    labels:
      - 'pr/translation'
  - title: '### DOCUMENTATION:'
    labels:
      - 'pr/documentation'

exclude-labels:
  - 'ignore-changelog'
  - 'tools'

change-template: '* $TITLE (#$NUMBER) by $AUTHOR'
template: |
  _Requires the latest Version of [CBA](https://github.com/CBATeam/CBA_A3) and [ACE](https://github.com/acemod/ACE3)._

  ## Summary

  ## Changelog

  $CHANGES

  ## Contributors

  $CONTRIBUTORS

replacers:
  # Category titles
  # Der Release Drafter macht die Kategorie automatisch als ## Heading
  # und wir wollen sie als ### Heading haben
  - search: '/\#\# (\#\#\# (NEU|REPARIERT|VERBESSERT|VERÄNDERT|EINSTELLUNGEN|ÜBERSETZUNGEN|DOKUMENTATION):)/g'
    replace: '$1'
