mainprefix = "z"
prefix = "aslr"

name = "Advanced Slingloading Redux"

[properties]
author = "Andx"
url = "https://github.com/Andx667/advanced_slingloading_redux"

[binarize]
# enabled = true # Default: true

[files]
include = [
    "mod.cpp",
    "meta.cpp",
    "/img/*.png",
    "/img/*.paa",
    "LICENSE.md",
    "README.md",
]

exclude = [
    "*.psd",        # By default this list is empty
    "/.vscode/",
]

[version]
# path = "addons/main/script_version.hpp" # Default
# major = 0 # Overrides path when set
# minor = 1
# patch = 1
git_hash = 0 # Default: 8
