#include "..\script_component.hpp"

/*
* Author: Zorn
* Function to get the Hooks / Sling Load Points.
*
*
* Arguments:
*
* Return Value:
* None
*
* Example:
* ['something', player] call prefix_component_fnc_functionname
*
* Public: No
*/

params [ "_vehicleClass" ];

// 1. Check if is kindOf ASLR_hooks
// 1.B If not, get autogenerated hook points from
